In [146]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#KOSPI

In [147]:
df_KOSPI_200 = pd.read_csv(r"KOSPI 50 Historical Data.csv")

In [148]:
df_KOSPI_200['Date'] = pd.to_datetime(df_KOSPI_200['Date'])
df_KOSPI_200 = df_KOSPI_200.sort_values(by='Date').reset_index(drop=True)
df_KOSPI_200.set_index('Date', inplace=True)

In [149]:
df_KOSPI_200['Price'] = df_KOSPI_200['Price'].str.replace(',', '').str.replace(' ', '')
df_KOSPI_200['Price'] = pd.to_numeric(df_KOSPI_200['Price'], errors='coerce')

In [150]:
prices = df_KOSPI_200['Price']
returns_KOSPI_200 = np.log(prices / prices.shift(1)).dropna()
returns_KOSPI_200 = returns_KOSPI_200.to_frame(name='Return')

===============================================================================

#KOSPI in Normal Market

In [151]:
df_KOSPI_Norm = pd.DataFrame()

In [152]:
df_KOSPI_Norm['Use'] = df_KOSPI_200.loc[df_KOSPI_200.index > '2021-01-02', 'Price']
df_KOSPI_Norm['Use']

Date
2021-01-04    2802.02
2021-01-05    2842.83
2021-01-06    2813.93
2021-01-07    2880.32
2021-01-08    3031.59
               ...
2025-05-20    2360.29
2025-05-21    2374.08
2025-05-22    2341.10
2025-05-23    2340.60
2025-05-26    2385.39
Name: Use, Length: 1079, dtype: float64

In [153]:
prices = df_KOSPI_Norm['Use']
re_KOSPI_Norma = np.log(prices / prices.shift(1)).dropna()
re_KOSPI_Norma = re_KOSPI_Norma.to_frame(name='Return')

In [154]:
re_KOSPI_Norma.describe().round(4)*100

          Return
count  107800.00
mean       -0.01
std         1.23
min        -9.46
25%        -0.75
50%        -0.01
75%         0.75
max         6.60

===============================================================================

#ASX All Situation

In [155]:
df_ASX = pd.read_csv(r"S&P_ASX 200 Historical Data.csv")

In [156]:
df_ASX['Date'] = pd.to_datetime(df_ASX['Date'])
df_ASX = df_ASX.sort_values(by='Date').reset_index(drop=True)
df_ASX.set_index('Date', inplace=True)
df_ASX['Price'] = df_ASX['Price'].str.replace(',', '', regex=False)
df_ASX['Price'] = pd.to_numeric(df_ASX['Price'], errors='coerce')

In [157]:
prices = df_ASX['Price']
returns_ASX = np.log(prices / prices.shift(1)).dropna()
returns_ASX = returns_ASX.to_frame(name='Return')

In [158]:
returns_ASX.describe().round(4)*100

          Return
count  262900.00
mean        0.02
std         0.97
min       -10.20
25%        -0.43
50%         0.08
75%         0.52
max         6.77

===============================================================================

#ASX in Normal Market

In [159]:
df_ASX_Norm = pd.DataFrame()

In [160]:
df_ASX_Norm['Use'] = df_ASX.loc[df_ASX.index > '2021-01-02', 'Price']
df_ASX_Norm['Use']

Date
2021-01-04    6684.2
2021-01-05    6681.9
2021-01-06    6607.1
2021-01-07    6712.0
2021-01-08    6757.9
               ...
2025-05-20    8343.3
2025-05-21    8386.8
2025-05-22    8348.7
2025-05-23    8360.9
2025-05-26    8361.0
Name: Use, Length: 1110, dtype: float64

In [161]:
prices = df_ASX_Norm['Use']
re_ASX_Norm = np.log(prices / prices.shift(1)).dropna()
re_ASX_Norm = re_ASX_Norm.to_frame(name='Return')  
re_ASX_Norm

              Return
Date
2021-01-05 -0.000344
2021-01-06 -0.011258
2021-01-07  0.015752
2021-01-08  0.006815
2021-01-11 -0.009023
...              ...
2025-05-20  0.005794
2025-05-21  0.005200
2025-05-22 -0.004553
2025-05-23  0.001460
2025-05-26  0.000012

[1109 rows x 1 columns]

===============================================================================

#FTSE 250

In [162]:
df_FTSE_250 = pd.read_csv(r"FTSE Mid-Cap 250 Historical Data.csv")

In [163]:
df_FTSE_250['Date'] = pd.to_datetime(df_FTSE_250['Date'])
df_FTSE_250 = df_FTSE_250.sort_values(by='Date').reset_index(drop=True)
df_FTSE_250.set_index('Date', inplace=True)
df_FTSE_250['Price'] = df_FTSE_250['Price'].str.replace(',', '', regex=False)
df_FTSE_250['Price'] = pd.to_numeric(df_FTSE_250['Price'], errors='coerce')

In [164]:
prices = df_FTSE_250['Price']
returns_FTSE_250 = np.log(prices / prices.shift(1)).dropna()
returns_FTSE_250 = returns_FTSE_250.to_frame(name='Return')

===============================================================================

#FTSE 250 Exclude COVID

In [165]:
df_FTSE_Norm = pd.DataFrame()

In [166]:
df_FTSE_Norm['Use'] = df_FTSE_250.loc[df_FTSE_250.index > '2021-01-02', 'Price']
df_FTSE_Norm['Use']

Date
2021-01-04    20537.89
2021-01-05    20717.37
2021-01-06    20973.16
2021-01-07    21009.86
2021-01-08    21064.24
                ...
2025-05-19    20961.09
2025-05-20    21096.44
2025-05-21    20949.67
2025-05-22    20799.66
2025-05-23    20708.72
Name: Use, Length: 1107, dtype: float64

In [167]:
prices = df_FTSE_Norm['Use']
re_FTSE_Norm = np.log(prices / prices.shift(1)).dropna()
re_FTSE_Norm = re_FTSE_Norm.to_frame(name='Return')  
re_FTSE_Norm

              Return
Date
2021-01-05  0.008701
2021-01-06  0.012271
2021-01-07  0.001748
2021-01-08  0.002585
2021-01-11 -0.013772
...              ...
2025-05-19 -0.000533
2025-05-20  0.006436
2025-05-21 -0.006981
2025-05-22 -0.007186
2025-05-23 -0.004382

[1106 rows x 1 columns]

===============================================================================








#FTSE 100

In [168]:
df_FTSE_100 = pd.read_csv(r"FTSE 100 Historical Data.csv")

In [169]:
df_FTSE_100['Date'] = pd.to_datetime(df_FTSE_100['Date'])
df_FTSE_100 = df_FTSE_100.sort_values(by='Date').reset_index(drop=True)
df_FTSE_100.set_index('Date', inplace=True)
df_FTSE_100['Price'] = df_FTSE_100['Price'].str.replace(',', '', regex=False)
df_FTSE_100['Price'] = pd.to_numeric(df_FTSE_100['Price'], errors='coerce')

In [170]:
prices = df_FTSE_100['Price']
returns_FTSE_100 = np.log(prices / prices.shift(1)).dropna()
returns_FTSE_100 = returns_FTSE_100.to_frame(name='Return')

===============================================================================








#FTSE 100 Exclude COVID

In [171]:
df_FTSE100_Norm = pd.DataFrame()

In [172]:
df_FTSE100_Norm['Use'] = df_FTSE_100.loc[df_FTSE_100.index > '2021-01-02', 'Price']
df_FTSE100_Norm['Use']

Date
2021-01-04    6571.88
2021-01-05    6612.25
2021-01-06    6841.86
2021-01-07    6856.96
2021-01-08    6873.26
               ...
2025-05-19    8699.31
2025-05-20    8781.12
2025-05-21    8786.46
2025-05-22    8739.26
2025-05-23    8717.97
Name: Use, Length: 1107, dtype: float64

In [173]:
prices = df_FTSE100_Norm['Use']
re_FTSE100_Norm = np.log(prices / prices.shift(1)).dropna()
re_FTSE100_Norm = re_FTSE100_Norm.to_frame(name='Return')  
re_FTSE100_Norm

              Return
Date
2021-01-05  0.006124
2021-01-06  0.034136
2021-01-07  0.002205
2021-01-08  0.002374
2021-01-11 -0.010939
...              ...
2025-05-19  0.001697
2025-05-20  0.009360
2025-05-21  0.000608
2025-05-22 -0.005386
2025-05-23 -0.002439

[1106 rows x 1 columns]

===============================================================================

#RESULT & VISUALIZATION

In [174]:
returns_dict = {
    "ret_KOSPI (KRW)": returns_KOSPI_200,
    "ret_KOSPI_Exclude_COVID (KRW)": re_KOSPI_Norma,
    "ret_ASX (USD)": returns_ASX,
    "ret_ASX_Exclude_COVID (AUD)": re_ASX_Norm,
    "ret_FTSE_250 (GBP)":returns_FTSE_250,
    "ret_FTSE_250_Exclude_COVID (GBP)":re_FTSE_Norm,
    "ret_FTSE_100 (GBP)":returns_FTSE_100,
    "ret_FTSE_100_Exclude_COVID (GBP)":re_FTSE100_Norm
}

price_dict = {
    "ret_KOSPI (KRW)": df_KOSPI_200['Price'],
    "ret_KOSPI_Exclude_COVID (KRW)": df_KOSPI_Norm['Use'],
    "ret_ASX (USD)": df_ASX['Price'],
    "ret_ASX_Exclude_COVID (AUD)": df_ASX_Norm['Use'],
    "ret_FTSE_250 (GBP)":df_FTSE_250['Price'],
    "ret_FTSE_250_Exclude_COVID (GBP)":df_FTSE_Norm['Use'],
    "ret_FTSE_100 (GBP)":df_FTSE_100['Price'],
    "ret_FTSE_100_Exclude_COVID (GBP)":df_FTSE100_Norm['Use']
}

In [175]:
max_abs_change_dict = {}

for name, series in returns_dict.items():
    if isinstance(series, pd.DataFrame):
        series = series.mean(axis=1)

    # หา abs เปลี่ยนแปลงแรงสุด
    abs_series = series.abs()
    max_idx = abs_series.idxmax()
    max_change = abs_series.loc[max_idx]

    # หา Pt และ Pt+1 จากราคาจริง (ต้องมี price_series[name] คู่กัน)
    try:
        price_series = price_dict[name]  # <- ต้องสร้าง price_dict ก่อนนะจ๊ะ
        pt = price_series.shift(1).loc[max_idx]
        pt1 = price_series.loc[max_idx]
    except:
        pt, pt1 = None, None

    max_abs_change_dict[name] = {
        "Max_Abs_Change": max_change,
        "Date": max_idx,
        "Pt": round(pt, 4) if pt is not None else None,
        "Pt+1": round(pt1, 4) if pt1 is not None else None
    }

In [176]:
max_abs_change_dict

{'ret_KOSPI (KRW)': {'Max_Abs_Change': 0.09462205690861457,
  'Date': Timestamp('2024-08-05 00:00:00'),
  'Pt': 2523.39,
  'Pt+1': 2295.57},
 'ret_KOSPI_Exclude_COVID (KRW)': {'Max_Abs_Change': 0.09462205690861457,
  'Date': Timestamp('2024-08-05 00:00:00'),
  'Pt': 2523.39,
  'Pt+1': 2295.57},
 'ret_ASX (USD)': {'Max_Abs_Change': 0.10203030652983877,
  'Date': Timestamp('2020-03-16 00:00:00'),
  'Pt': 5539.3,
  'Pt+1': 5002.0},
 'ret_ASX_Exclude_COVID (AUD)': {'Max_Abs_Change': 0.044370403329057055,
  'Date': Timestamp('2025-04-10 00:00:00'),
  'Pt': 7375.0,
  'Pt+1': 7709.6},
 'ret_FTSE_250 (GBP)': {'Max_Abs_Change': 0.09820191297458289,
  'Date': Timestamp('2020-03-12 00:00:00'),
  'Pt': 17339.23,
  'Pt+1': 15717.42},
 'ret_FTSE_250_Exclude_COVID (GBP)': {'Max_Abs_Change': 0.04499178801984924,
  'Date': Timestamp('2025-04-04 00:00:00'),
  'Pt': 19210.51,
  'Pt+1': 18365.35},
 'ret_FTSE_100 (GBP)': {'Max_Abs_Change': 0.11512428334613645,
  'Date': Timestamp('2020-03-12 00:00:00'),
  'Pt': 5876.52,
  'Pt+1': 5237.48},
 'ret_FTSE_100_Exclude_COVID (GBP)': {'Max_Abs_Change': 0.050799440633845505,
  'Date': Timestamp('2025-04-04 00:00:00'),
  'Pt': 8474.74,
  'Pt+1': 8054.98}}

In [177]:
tick_size_dict = {
    "KOSPI": 0.01,
    "ASX": 1,
    "FTSE":0.5
}

contract_size_dict = {
    "KOSPI": 250000,
    "ASX": 10,
    "FTSE":10
}
somc_dict = {
    "KOSPI": "10 Ticks * Tick Size * Contract Size",
    "ASX": " $0.50 per contract for certain equities",
    "FTSE":" SCRAF Ratio * SOM Rate"
}

In [178]:
def extract_base_name(name):
    if "KOSPI" in name:
        return "KOSPI"
    elif "ASX" in name:
        return "ASX"
    elif "SET50" in name:
        return "SET50"
    elif "FTSE" in name:
        return "FTSE"
    else:
        return name

In [179]:
summary_data = []

for name, detail in max_abs_change_dict.items():
    base = extract_base_name(name)

    tick = tick_size_dict.get(base, None)
    contract = contract_size_dict.get(base, None)
    somc = somc_dict.get(base, "Unknown")

    summary_data.append({
        "Instrument": name,
        "Tick_Size": tick,
        "Contract_Size": contract,
        "Max_Abs_Change": detail.get("Max_Abs_Change", None),
        "Date": detail.get("Date", None),
        "Pt": detail.get("Pt", None),
        "Pt+1": detail.get("Pt+1", None),
        "SOMC_Policy": somc
    })

# 📊 สร้าง DataFrame
df_summary = pd.DataFrame(summary_data).set_index("Instrument")

In [180]:
df_summary

,Tick_Size,Contract_Size,Max_Abs_Change,Date,Pt,Pt+1,SOMC_Policy
Instrument,,,,,,,
ret_KOSPI (KRW),0.01,250000,0.094622,2024-08-05,2523.39,2295.57,10 Ticks * Tick Size * Contract Size
ret_KOSPI_Exclude_COVID (KRW),0.01,250000,0.094622,2024-08-05,2523.39,2295.57,10 Ticks * Tick Size * Contract Size
ret_ASX (USD),1.00,10,0.102030,2020-03-16,5539.30,5002.00,$0.50 per contract for certain equities
ret_ASX_Exclude_COVID (AUD),1.00,10,0.044370,2025-04-10,7375.00,7709.60,$0.50 per contract for certain equities
ret_FTSE_250 (GBP),0.50,10,0.098202,2020-03-12,17339.23,15717.42,SCRAF Ratio * SOM Rate
ret_FTSE_250_Exclude_COVID (GBP),0.50,10,0.044992,2025-04-04,19210.51,18365.35,SCRAF Ratio * SOM Rate
ret_FTSE_100 (GBP),0.50,10,0.115124,2020-03-12,5876.52,5237.48,SCRAF Ratio * SOM Rate
ret_FTSE_100_Exclude_COVID (GBP),0.50,10,0.050799,2025-04-04,8474.74,8054.98,SCRAF Ratio * SOM Rate

In [181]:
from IPython.display import display
display(df_summary)

,Tick_Size,Contract_Size,Max_Abs_Change,Date,Pt,Pt+1,SOMC_Policy
Instrument,,,,,,,
ret_KOSPI (KRW),0.01,250000,0.094622,2024-08-05,2523.39,2295.57,10 Ticks * Tick Size * Contract Size
ret_KOSPI_Exclude_COVID (KRW),0.01,250000,0.094622,2024-08-05,2523.39,2295.57,10 Ticks * Tick Size * Contract Size
ret_ASX (USD),1.00,10,0.102030,2020-03-16,5539.30,5002.00,$0.50 per contract for certain equities
ret_ASX_Exclude_COVID (AUD),1.00,10,0.044370,2025-04-10,7375.00,7709.60,$0.50 per contract for certain equities
ret_FTSE_250 (GBP),0.50,10,0.098202,2020-03-12,17339.23,15717.42,SCRAF Ratio * SOM Rate
ret_FTSE_250_Exclude_COVID (GBP),0.50,10,0.044992,2025-04-04,19210.51,18365.35,SCRAF Ratio * SOM Rate
ret_FTSE_100 (GBP),0.50,10,0.115124,2020-03-12,5876.52,5237.48,SCRAF Ratio * SOM Rate
ret_FTSE_100_Exclude_COVID (GBP),0.50,10,0.050799,2025-04-04,8474.74,8054.98,SCRAF Ratio * SOM Rate